name: nero_restaurant
description: Nero Restaurant Template

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.1
  firebase_auth: "^0.5.20"
  flutter_firebase_ui: "^0.0.11"
  firebase_messaging: ^1.0.2
  cached_network_image: "^0.4.1+1"
  qr_flutter: ^1.1.1
#  flutter_fab_dialer: "^0.0.5"
  flutter_circular_chart: "^0.1.0"
  sliver_fab: "^0.1.0"
  flutter_webview_plugin: "0.2.1+2"
  duration: "^2.0.0"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/ndm_logo.jpg
    - assets/images/order_card.jpg
    - assets/images/google_signin_button.png
    - assets/images/empty-cart.png
    - assets/images/empty-favorites.png
    - assets/images/empty-previous.png
    - assets/images/special.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
        - asset: assets/fonts/RobotoSlab-Light.ttf
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Thin.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf


